-- ==========================================
-- BITRAXX ICO PRESALE SYSTEM SCHEMA MIGRATION
-- Database: Supabase / PostgreSQL (15+)
-- File: backend/supabase_schema.sql
-- ==========================================

-- Clean up existing elements if running multiple times
DROP FUNCTION IF EXISTS public.handle_successful_transaction();
DROP FUNCTION IF EXISTS public.process_referral_reward(VARCHAR(255), NUMERIC(16, 4), NUMERIC(24, 6));
DROP TABLE IF EXISTS public.user_preferences CASCADE;
DROP TABLE IF EXISTS public.accepted_tokens CASCADE;
DROP TABLE IF EXISTS public.company_wallets CASCADE;
DROP TABLE IF EXISTS public.announcements CASCADE;
DROP TABLE IF EXISTS public.referrals CASCADE;
DROP TABLE IF EXISTS public.transactions CASCADE;
DROP TABLE IF EXISTS public.presale_stages CASCADE;
DROP TABLE IF EXISTS public.investors CASCADE;

DROP TYPE IF EXISTS verification_status_type;
DROP TYPE IF EXISTS transaction_status_type;
DROP TYPE IF EXISTS phase_status_type;
DROP TYPE IF EXISTS payout_status_type;
DROP TYPE IF EXISTS token_type;

-- 1. Create Enums and Types
CREATE TYPE verification_status_type AS ENUM ('Verified', 'Pending', 'Flagged');
CREATE TYPE transaction_status_type AS ENUM ('Success', 'Pending', 'Failed');
CREATE TYPE phase_status_type AS ENUM ('Upcoming', 'Active', 'Completed', 'Paused');
CREATE TYPE payout_status_type AS ENUM ('Pending', 'Distributed');
CREATE TYPE token_type AS ENUM ('Stablecoin', 'Native');

-- 2. Create Investors Table
CREATE TABLE public.investors (
    wallet_address VARCHAR(255) PRIMARY KEY, -- Lowercase normalized Ethereum/BSC hex address
    verification_status verification_status_type DEFAULT 'Pending'::verification_status_type NOT NULL,
    total_invested_usd NUMERIC(16, 4) DEFAULT 0.0000 NOT NULL,
    brx_allocation NUMERIC(24, 6) DEFAULT 0.000000 NOT NULL,
    latest_network VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indexes for performance
CREATE INDEX idx_investors_status ON public.investors(verification_status);
CREATE INDEX idx_investors_last_seen ON public.investors(last_seen_at);

-- 3. Create Presale Stages Table
CREATE TABLE public.presale_stages (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price_usd NUMERIC(12, 6) NOT NULL, -- Dollar value of 1 BRX token
    hard_cap_usd NUMERIC(16, 2) NOT NULL, -- Hard limit for funding in USD
    raised_usd NUMERIC(16, 2) DEFAULT 0.00 NOT NULL, -- Total funds raised in this stage
    status phase_status_type DEFAULT 'Upcoming'::phase_status_type NOT NULL,
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX idx_stages_status ON public.presale_stages(status);

-- 4. Create Transactions Table
CREATE TABLE public.transactions (
    tx_hash VARCHAR(66) PRIMARY KEY, -- Lowercase normalized transaction hash (66 characters with 0x)
    wallet_address VARCHAR(255) REFERENCES public.investors(wallet_address) ON DELETE CASCADE NOT NULL,
    payment_token VARCHAR(10) NOT NULL, -- e.g., USDT, ETH, BNB
    amount_paid NUMERIC(28, 18) NOT NULL, -- Amount paid in raw crypto decimals
    amount_paid_usd NUMERIC(16, 4) DEFAULT 0.0000 NOT NULL, -- Valuation in USD at capture time
    brx_quantity NUMERIC(24, 6) NOT NULL, -- Amount of BRX tokens allocated
    network VARCHAR(50) NOT NULL, -- e.g., BSC, ETH
    status transaction_status_type DEFAULT 'Pending'::transaction_status_type NOT NULL,
    stage_id INT REFERENCES public.presale_stages(id),
    captured_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    confirmed_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_transactions_wallet ON public.transactions(wallet_address);
CREATE INDEX idx_transactions_status ON public.transactions(status);
CREATE INDEX idx_transactions_captured ON public.transactions(captured_at);

-- 5. Create Referrals Table
CREATE TABLE public.referrals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    referrer_address VARCHAR(255) REFERENCES public.investors(wallet_address) ON DELETE RESTRICT NOT NULL,
    referred_address VARCHAR(255) REFERENCES public.investors(wallet_address) ON DELETE RESTRICT UNIQUE NOT NULL,
    referred_volume_usd NUMERIC(16, 4) DEFAULT 0.0000 NOT NULL, -- Sales volume generated by referred wallet
    reward_brx NUMERIC(24, 6) DEFAULT 0.000000 NOT NULL, -- Earned BRX tokens (5% of purchase quantity)
    payout_status payout_status_type DEFAULT 'Pending'::payout_status_type NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX idx_referrals_referrer ON public.referrals(referrer_address);
CREATE INDEX idx_referrals_referred ON public.referrals(referred_address);

-- 6. Create Announcements Table
CREATE TABLE public.announcements (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    tag VARCHAR(50) NOT NULL, -- Feature, Important, Ecosystem, Docs
    description TEXT NOT NULL,
    color VARCHAR(50) DEFAULT 'text-acid-lime' NOT NULL,
    is_visible BOOLEAN DEFAULT TRUE NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX idx_announcements_published ON public.announcements(published_at) WHERE is_visible = TRUE;

-- 7. Create Company Wallets Table
CREATE TABLE public.company_wallets (
    id VARCHAR(50) PRIMARY KEY, -- treasury, marketing
    label VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    description TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Create Accepted Tokens Table
CREATE TABLE public.accepted_tokens (
    id SERIAL PRIMARY KEY,
    name VARCHAR(10) NOT NULL, -- USDT, ETH, BNB
    token_type token_type NOT NULL, -- Stablecoin, Native
    status VARCHAR(20) DEFAULT 'Enabled' NOT NULL, -- Enabled, Disabled
    network VARCHAR(50) NOT NULL -- BSC, ETH
);

-- 9. Create User Notification Preferences Table
CREATE TABLE public.user_preferences (
    wallet_address VARCHAR(255) PRIMARY KEY REFERENCES public.investors(wallet_address) ON DELETE CASCADE,
    purchase_confirmations BOOLEAN DEFAULT TRUE NOT NULL,
    phase_adjustments BOOLEAN DEFAULT TRUE NOT NULL,
    referral_rewards BOOLEAN DEFAULT TRUE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ========================================================
-- DATABASE TRIGGERS & PROCEDURES (Core Presale Automation)
-- ========================================================

-- Trigger function: Process referral rewards upon successful transaction
CREATE OR REPLACE FUNCTION public.process_referral_reward(
    p_referred VARCHAR(255),
    p_volume_usd NUMERIC(16, 4),
    p_quantity_brx NUMERIC(24, 6)
)
RETURNS VOID AS $$
DECLARE
    v_referrer VARCHAR(255);
    v_reward_brx NUMERIC(24, 6);
BEGIN
    -- Query if referred wallet was invited by an active referrer
    SELECT referrer_address INTO v_referrer 
    FROM public.referrals 
    WHERE referred_address = p_referred LIMIT 1;

    -- If referred by someone, credit their account with 5% reward
    IF v_referrer IS NOT NULL THEN
        v_reward_brx := p_quantity_brx * 0.050000;

        UPDATE public.referrals
        SET 
            referred_volume_usd = referred_volume_usd + p_volume_usd,
            reward_brx = reward_brx + v_reward_brx
        WHERE referred_address = p_referred;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger function: Handle transactions when status is set to 'Success'
CREATE OR REPLACE FUNCTION public.handle_successful_transaction()
RETURNS TRIGGER AS $$
BEGIN
    -- Only trigger totals aggregation if the state transitions to 'Success'
    IF NEW.status = 'Success'::transaction_status_type AND (OLD IS NULL OR OLD.status <> 'Success'::transaction_status_type) THEN
        -- 1. Increment total values inside investors table
        UPDATE public.investors
        SET 
            total_invested_usd = total_invested_usd + COALESCE(NEW.amount_paid_usd, 0.0000),
            brx_allocation = brx_allocation + COALESCE(NEW.brx_quantity, 0.000000),
            last_seen_at = timezone('utc'::text, now())
        WHERE wallet_address = NEW.wallet_address;

        -- 2. Increment total raised inside presale_stages table
        IF NEW.stage_id IS NOT NULL THEN
            UPDATE public.presale_stages
            SET raised_usd = raised_usd + COALESCE(NEW.amount_paid_usd, 0.00)
            WHERE id = NEW.stage_id;
        END IF;

        -- 3. Execute referral reward calculation
        PERFORM public.process_referral_reward(NEW.wallet_address, NEW.amount_paid_usd, NEW.brx_quantity);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Attach the trigger to transactions
CREATE TRIGGER trg_on_transaction_success
    AFTER INSERT OR UPDATE ON public.transactions
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_successful_transaction();


-- ========================================================
-- DEFAULT MOCK SEED INJECTIONS (Matches original designs)
-- ========================================================

-- Initial Company Wallets
INSERT INTO public.company_wallets (id, label, address, description) VALUES
('treasury', 'Treasury Wallet', '0x71C7656EC7ab88b098defB751B7401B5f6d8976F', 'Main treasury storage where presale stablecoins and native funds are forwarded.'),
('marketing', 'Marketing Fund', '0x250F29d8EC2ab88b098defB751B7401B5f6d8976F', 'Wallet allocated for community payouts, referral reward reserves, and global growth.');

-- Initial Accepted Tokens
INSERT INTO public.accepted_tokens (name, token_type, status, network) VALUES
('USDT', 'Stablecoin', 'Enabled', 'BSC'),
('ETH', 'Native', 'Enabled', 'ETH'),
('BNB', 'Native', 'Enabled', 'BSC'),
('USDT', 'Stablecoin', 'Enabled', 'ETH');

-- Initial Stages
INSERT INTO public.presale_stages (id, name, price_usd, hard_cap_usd, raised_usd, status, start_date, end_date) VALUES
(1, 'Private Sale', 0.002000, 1000000.00, 0.00, 'Completed', '2026-01-01 00:00:00+00', '2026-01-31 23:59:59+00'),
(2, 'ICO Phase 1', 0.005000, 6000000.00, 0.00, 'Active', '2026-02-01 00:00:00+00', '2026-06-30 23:59:59+00'),
(3, 'ICO Phase 2', 0.008000, 10000000.00, 0.00, 'Upcoming', '2026-07-01 00:00:00+00', '2026-10-31 23:59:59+00');

-- Initial Announcements
INSERT INTO public.announcements (title, tag, description, color) VALUES
('Phase 2 Launch Approaching', 'Important', 'Private Sale Phase 1 is nearing completion. Prepare for upcoming pricing adjustments. Phase 2 will start on June 1st with a price of $0.0075 per BRX.', 'text-red-400'),
('Dashboard Upgrade Released', 'Feature', 'New allocation tracking and referral analytics are now available. We''ve added more detailed transaction history and real-time progress bars.', 'text-blue-400'),
('Partnership with Quantum Labs', 'Ecosystem', 'We are excited to announce our technical partnership with Quantum Labs to enhance our Layer 2 scaling solutions.', 'text-acid-lime'),
('Tokenomics Paper Update', 'Docs', 'We have updated our tokenomics paper with more details on the ecosystem fund and developer grants.', 'text-purple-400');
